### ISSUE TITLE
Swift 3 support?

### ISSUE THREAD

**Issue by danielt1263** [CrossWaterBridge/Attributed#3]
I see a branch for swift 2.3. Are there also plans to support Swift 3?

**Comment by hiltonc** [comment]
Yes. I'm moving all my projects to Swift 2.3 currently. When I'm ready to migrate my projects to Swift 3 I'll migrate `master`. You're welcome to do so if you need it sooner.

**Comment by hiltonc** [comment]
Attributed now supports Swift 3.
